services:
  - type: pserv  # 👈 This is the key change
    name: mysql
    runtime: docker
    image:
      url: mayalevi/mysql-with-superstore
    plan: starter
    envVars:
      - key: MYSQL_ROOT_PASSWORD
        value: SecurePassword123
    disk:
      name: mysql-data
      mountPath: /var/lib/mysql
      sizeGB: 1