services:
  - type: web
    name: mysql
    env: docker
    image:
      url: mayalevi/mysql-with-superstore
    plan: starter
    envVars:
      - key: MYSQL_ROOT_PASSWORD
        value: SecurePassword123
    disk:
      name: mysql-data
      mountPath: /var/lib/mysql
      sizeGB: 1

  - type: web
    name: backend
    env: docker
    image:
      url: mayalevi/backend-app
    plan: starter
    envVars:
      - key: DATABASE_URL
        value: mysql://root:SecurePassword123@mysql:3306/superstore
    healthCheckPath: /

  - type: web
    name: react
    env: docker
    image:
      url: mayalevi/react-app
    plan: starter
