services:
  - type: web
    name: mysql
    env: docker
    image: mayalevi/mysql-with-superstore
    plan: starter
    ingress:
      type: internal
    envVars:
      - key: MYSQL_ROOT_PASSWORD
        value: SecurePassword123
    disk:
      name: mysql-data
      mountPath: /var/lib/mysql
      sizeGB: 1

  - type: web
    name: backend
    env: docker
    image: mayalevi/backend-app
    plan: starter
    entrypoint: ["./entrypoint.sh"]
    envVars:
      - key: DATABASE_URL
        value: mysql://root:SecurePassword123@mysql:3306/superstore
    dependsOn:
      - mysql
    healthCheckPath: /
    ports:
      - port: 8000

  - type: web
    name: react
    env: docker
    image: mayalevi/react-app
    plan: starter
    dependsOn:
      - backend
    ports:
      - port: 80
